### ISSUE TITLE
Issue with pm.data.wepp

### ISSUE THREAD

**Issue by Jaspergeipel** [FRESNA/powerplantmatching#18]
Hello Fabian,
I just noticed that there seems to be an issue with the import of WEPP data:
1. "source_file" should probably be replaced by "fn"
2. WEPP uses "correct_manually" from utils.py which in turn relies on data_config which does not exist. 
```
def correct_manually(df, name, config=None):\
  from. data import data_config
```
Error Message:
File "C:\ProgramData\Anaconda3\lib\site-packages\powerplantmatching\utils.py", line 143, in correct_manually
    from .data import data_config
ImportError: cannot import name 'data_config' from 'powerplantmatching.data' (C:\ProgramData\Anaconda3\lib\site-packages\powerplantmatching\data.py)

**Comment by Jaspergeipel** [comment]
Addon: 

- outcommenting the line 816: `#.pipe(correct_manually, 'WEPP', config=config)` enables to import the full 31945 row long wepp dataframe via ppm.data.WEPP()
- However running `ppm.powerplants(from_url=False, update=True)` provides the following error massage, 

File "C:\Users\geipel\Desktop\JRC_capacities_processing\Pmtest.py", line 51, in <module>
    df = ppm.powerplants(from_url=False, update=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\powerplantmatching\collection.py", line 221, in matched_data
    **extendby_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\powerplantmatching\heuristics.py", line 75, in extend_by_non_matched
    config=config, **aggkwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\powerplantmatching\cleaning.py", line 341, in aggregate_units
    for c in df.Country.unique()])

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 281, in concat
    sort=sort,

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 329, in __init__
    raise ValueError("No objects to concatenate")

ValueError: No objects to concatenate

**Comment by FabianHofmann** [comment]
Hey @Jaspergeipel , 
this comes from the fact that I don't have the WEPP data, hence the support for it is not well covered :)   The second error seems to be the same that you talked about in the mail. I'm having a look at it now.

**Comment by FabianHofmann** [comment]
The second error should now be solved, please check on the current master. Note that in your config, you most probable have WEPP still in `fully_included_sources` (which does not really makes sense). This raises a warning now

**Comment by Jaspergeipel** [comment]
Unfortunatly the "ValueError: No objects to concatenate" error seems to persist:
It occurs if I make one of the following changes config.yaml:
- removing specific target_fueltypes such as Hydro, 
- if I outcomment specific countries
- if I include the WEPP option  from matching_sources

runfile('C:/Users/geipel/Desktop/Neuer Ordner/Pmtest.py', wdir='C:/Users/geipel/Desktop/Neuer Ordner')
WARNING:powerplantmatching.matching:Non-existing saved matches for dataset 'CARMA', 'WEPP' continuing by matching again
WARNING:powerplantmatching.matching:Non-existing saved matches for dataset 'ENTSOE', 'WEPP' continuing by matching again
WARNING:powerplantmatching.matching:Non-existing saved matches for dataset 'GEO', 'WEPP' continuing by matching again
WARNING:powerplantmatching.matching:Non-existing saved matches for dataset 'GPD', 'WEPP' continuing by matching again
WARNING:powerplantmatching.matching:Non-existing saved matches for dataset 'OPSD', 'WEPP' continuing by matching again
Traceback (most recent call last):

  File "C:\Users\geipel\Desktop\Neuer Ordner\Pmtest.py", line 50, in <module>
    df = ppm.powerplants(from_url=False, update=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\powerplantmatching\collection.py", line 221, in matched_data
    **extendby_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\powerplantmatching\heuristics.py", line 75, in extend_by_non_matched
    config=config, **aggkwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\powerplantmatching\cleaning.py", line 341, in aggregate_units
    for c in df.Country.unique()])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 281, in concat
    sort=sort,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 329, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by Jaspergeipel** [comment]
works smooth now. Issue most likely due to outcommented technologies in the config file
thanks
