### ISSUE TITLE
Problem with some power plants start year (DateIn)

### ISSUE THREAD

**Issue by Parisra** [FRESNA/powerplantmatching#71]
Hi there!

I've been running some simulations with the latest version of pypsa-eur-sec, but every-time I tried to do a myopic run, I got the following error:

Traceback (most recent call last):
  File "/home/parisr/projects/pypsa-eur-sec/.snakemake/scripts/tmpy5ti4rwe.add_existing_baseyear.py", line 491, in <module>
    add_power_capacities_installed_before_baseyear(n, grouping_years, costs, baseyear)
  File "/home/parisr/projects/pypsa-eur-sec/.snakemake/scripts/tmpy5ti4rwe.add_existing_baseyear.py", line 177, in add_power_capacities_installed_before_baseyear
    df_agg["grouping_year"] = np.take(
  File "<__array_function__ internals>", line 180, in take
  File "/home/parisr/miniconda3/envs/pypsa-eur/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/parisr/miniconda3/envs/pypsa-eur/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/parisr/miniconda3/envs/pypsa-eur/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
IndexError: index 9 is out of bounds for axis 0 with size 9

After some debugging, I realised there were some power plants in powerplants.csv that had their starting year after the last year in my grouping years (grouping_years: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019]). I changed my end year to 2022 instead of 2019, which solved the issue for some power plants, but then I noticed that there are currently 5 nuclear plants with a starting year of 2027, which seemed incorrect after searching their names in google. I managed to solve my problem by changing the starting years to 1983, 1996, etc. I just wanted to know if this was intentional or is it a mistake. Here are the links for the 5 power plants :

https://github.com/FRESNA/powerplantmatching/blob/b0e5a05773b88d40e99f73fd28606cdc6ea3b240/powerplants.csv#L86
https://github.com/FRESNA/powerplantmatching/blob/b0e5a05773b88d40e99f73fd28606cdc6ea3b240/powerplants.csv#L96
https://github.com/FRESNA/powerplantmatching/blob/b0e5a05773b88d40e99f73fd28606cdc6ea3b240/powerplants.csv#L401
https://github.com/FRESNA/powerplantmatching/blob/b0e5a05773b88d40e99f73fd28606cdc6ea3b240/powerplants.csv#L512
https://github.com/FRESNA/powerplantmatching/blob/b0e5a05773b88d40e99f73fd28606cdc6ea3b240/powerplants.csv#L559

Thanks :)

**Comment by FabianHofmann** [comment]
Hey @Parisra, thanks for reporting! This is indeed a bug that came from a from parsing of the Wikipedia data. I'll publish a new version during the next days in which this should be resolved.

**Comment by Parisra** [comment]
Great, happy to have helped. I ran the model again with the new version and did not get any errors, I will close the issue now.
